### ISSUE TITLE
Incorrect URL for 'BadBlock Whitelist'

### ISSUE THREAD

**Issue by xanderboy2001** [celenityy/adguard-home-settings#5]
The provided URL for BadBlock Whitelist returns a 404 error. The correct URL is https://codeberg.org/celenity/BadBlock/raw/branch/pages/abp/whitelist.txt

**Comment by celenityy** [comment]
Thanks for your issues!

I'm currently in the process of revamping this guide & some of my other guides, so this will be fixed soon. Appreciate your report.

The URL you should use in this case is `https://badblock.celenity.dev/abp/whitelist.txt`.
